# Generated by Django 4.0.4 on 2022-05-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("commentt", models.TextField(verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("availability", models.BooleanField()),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("phone", "phone"),
                            ("pc", "pc"),
                            ("laptop", "laptop"),
                            ("accessories", "accessories"),
                        ],
                        default="phone",
                        max_length=20,
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        default="no_image.jpeg", upload_to="product_image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
