# Generated by Django 4.0.4 on 2022-05-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="group",
            field=models.CharField(
                choices=[
                    ("laptop", "laptop"),
                    ("pc", "pc"),
                    ("phone", "phone"),
                    ("accessories", "accessories"),
                ],
                default="phone",
                max_length=20,
            ),
        ),
    ]
